version: '3.4'
services:

  nginx:
    stdin_open: true

  portainer:
    stdin_open: true

  pg:
    restart: always
    stdin_open: true
    environment:
      # - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - PGPORT=5432
    # ports: 
    #   - 5432:5432

  pgadmin:
    stdin_open: true
    environment: 
      - PGADMIN_DEFAULT_EMAIL=nazemi.works@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=secret
    # ports: 
    #   - 8005:80

  api:
    build: 
      dockerfile: ../api/Dockerfile
    stdin_open: true
    volumes: 
      - /app/node_modules 
      - ../api:/app
    environment:
      - PORT=5000
      - DBURL=pg
      - DBNAME=solarpg
      - NODE_ENV=development
      - PGPASS=secret
      - PGUSER=root
      - CORS=http://localhost:5000
    ports: 
      - 5000:5000
