version: '3.4'
services:

  nginx:
    stdin_open: true

  portainer:
    stdin_open: true

  pg:
    restart: always
    stdin_open: true
    environment:
      # - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=${}
      - POSTGRES_PASSWORD=${}
      - PGPORT=${}

  pgadmin:
    stdin_open: true
    environment: 
      - PGADMIN_DEFAULT_EMAIL=${}
      - PGADMIN_DEFAULT_PASSWORD=${}
    # ports: 
    #   - 8005:80

  api:
    image: penkong/vanillanodepg
    environment:
      - PORT=${}
      - DBURL=${}
      - DBNAME=solarpg
      - NODE_ENV=production
      - PGPASS=${}
      - PGUSER=${}
      - CORS=http://${}
      - JWT_KEY=${}
      - JWT_TTL=${}
    ports: 
      - ${}:${}
