version: '3.4'
services:

  nginx:
    image: 'nginx:stable-alpine'
    ports: 
      - 80:80
      - 443:443
    tty: true
    depends_on: 
      - apiauth
      - redis
      - pg
      - pgadmin
      - portainer
    volumes: 
      # remember!!!!!!! add trust proxy to nodejs services
      - ../app/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro #read only 

  portainer:
    image: portainer/portainer-ce
    restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock 

  pg:
    image: 'postgres:13.2-alpine'
    volumes: 
      - pgvol:/var/lib/postgresql/data 
      - ../app/services/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: 'dpage/pgadmin4'
    restart: always
    depends_on:
      - pg

  api:
    build: 
      context: ../app/services/auth
    restart: always
    depends_on:
      - pg
      - redis

volumes: 
  pgvol:
    driver: local
  portainer_data:
    driver: local
