POST http://localhost/v1/api/customer HTTP/1.1
content-type: application/json

{
    "first_name": "mazdak",
    "last_name": "nazemi",
    "email": "nazemi.works@gmail.com"
}

###
GET http://localhost/v1/api/customer HTTP/1.1

###
GET http://localhost/v1/api/customer/2 HTTP/1.1

###
PATCH  http://localhost/v1/api/customer/2 HTTP/1.1
content-type: application/json

{
    "last_name": "nazemiiii"
}

###
DELETE  http://localhost/v1/api/customer/2 HTTP/1.1
content-type: application/json

###
POST http://localhost/v1/api/product HTTP/1.1
content-type: application/json

{
    "component" : "battery",
    "model" : "x-s267-LE",
    "manufactor" : "samsung"
}

###
GET http://localhost/v1/api/product HTTP/1.1

###
PATCH http://localhost/v1/api/product/19 HTTP/1.1
content-type: application/json

{
    "model" : "x-s267-LS"
}

###
DELETE  http://localhost/v1/api/product/19 HTTP/1.1

###
POST http://localhost/v1/api/project HTTP/1.1
content-type: application/json

{
    "name" : "big project11",
    "customer" : "2",
    "construction_date" : "17.11.2023",
    "components_list": "[[14,05],[15,13],[17,13]]",
    "status" : "requested"
}

###
GET http://localhost/v1/api/project HTTP/1.1

###
PATCH http://localhost/v1/api/project/21 HTTP/1.1
content-type: application/json

{
    "components_list": "[[14,05],[15,13],[17,15]]"
}

###
DELETE  http://localhost/v1/api/project/12 HTTP/1.1